#include <iostream>
#include <string>
using std::cout;
using std::endl;
using std::string;

int main() {
    string secondo_appello[] = {
        "ANDREETTO ALESSIO",
        "BALDO LEONARDO",
        "BANZATO ALESSIO",
        "BARBIERO LINDA",
        "BASSANI FRANCESCO",
        "BASSO LEONARDO",
        "BENCIVELLI LORENZO",
        "BENIN ALESSANDRO",
        "BIANCHI ENRICO",
        "BILINSKI ELEONORA",
        "BISCONTIN GIULIO",
        "BOMBEN FILIPPO",
        "BONETTO EDOARDO",
        "BOTTACIN GIULIO",
        "BRESOLIN GIANLUCA",
        "BRESSAN STEFANO",
        "BROTTO DAVIDE",
        "BROTTO ROMINA",
        "BUSTREO ALESSANDRO",
        "CALEARO ROMEO",
        "CAMILLO MATTEO",
        "CANIATO SABRINA",
        "CAPPELLARI MARCO",
        "CAREGNATO SIMONE",
        "CARLESSO NICCOLÒ",
        "CARRARO ALESSANDRO",
        "CARRARO RICCARDO",
        "CAVALLI RICCARDO",
        "CHELHAOUI OSAMA",
        "CHILESE ELENA",
        "CINEL ALBERTO",
        "COSTANTIN RICCARDO ALBERTO",
        "COSTANTINI OSCAR",
        "CRISTELLON GIOVANNI",
        "CURCIO DAVIDE ANTONIO",
        "D'OVIDIO GIACOMO",
        "DALLA POZZA MATTIA",
        "DE LAURENTIS ARIANNA PIA",
        "DE PREZZO GIORGIO",
        "DOMUTA ALESSIA",
        "DONANZAN DAVIDE",
        "EGIDI ANNALISA",
        "FABBIAN RICCARDO",
        "FAVARETTO MARCO",
        "FELTRIN ALESSANDRO",
        "FELTRIN EMANUELE",
        "FERRO ELENA",
        "FILIPPINI GIOVANNI",
        "FONTANA RAFFAELE PAOLO",
        "FRIGO LEONARDO",
        "FURIOSO PATRICK",
        "GALLO EDOARDO",
        "GARDIN GIOVANNI",
        "GIACOMUZZO FRANCESCO",
        "GIURISATO ANDREA",
        "GOBBO MARCO",
        "GRANT JOSEPH",
        "GUSATTO DEREK",
        "HU GIULIA",
        "IGBINEDION OSAMWONYI EGHOSA MATTEO",
        "KONIECZNY OSCAR",
        "LAGO LEONARDO",
        "LAPENNA FRANCESCO",
        "LAZZARIN NICOLA",
        "LEONETTI ELIA",
        "LEONI PEDRO",
        "LOVATO YURI",
        "MAFFEI DAVIDE",
        "MAHDI MOUAD",
        "MANGOLINI ANDREA",
        "MANIERO MANUEL",
        "MARANA SEBASTIANO",
        "MARCHIORATO PIETRO GIOVANNI",
        "MARCHIORO MICHELE",
        "MARTINELLI DAVIDE",
        "MENEGHINI FABIO",
        "META ANITA",
        "MICHELAZZO ALBERTO",
        "MIOTTI NICOLA",
        "MORETTI GIOVANNI",
        "MORETTO NICHOLAS",
        "MOUNIB SAAD",
        "NARDO SILVIO",
        "NESLER MICHELE",
        "NIAGU ANA MARIA",
        "NORDIO ANNA",
        "OGNIBEN MICHELE",
        "ORLANDI GIACOMO",
        "PAN MATTHEW",
        "PANDOLFO MATTIA",
        "PARISE LUCA",
        "PASQUALOTTO LORENZO",
        "PASQUETTO RICCARDO",
        "PASSARELLA ALESSANDRO",
        "PERIC MARKO",
        "PIANON RAUL",
        "PICCOLI MARCO",
        "PONSO GIOVANNI",
        "PORPORATI DAVIDE",
        "POZZA FRANCESCO",
        "PRETO NICOLA",
        "RAMPAZZO ALESSANDRO OLAVI",
        "RIZZO ALBERTO",
        "ROSSI LUCA",
        "ROSSO CARLO",
        "ROSSON LORENZO",
        "ROVEA SILVIA",
        "SABBADIN FILIPPO",
        "SAVIO FRANCESCO",
        "SECURO LUCA",
        "SIGNORELLI IULIUS",
        "SIMIONATO RICCARDO",
        "SKËNDERI LISIEN",
        "SOLDÀ MATTEO",
        "STOCCO TOMMASO",
        "TECCHIATI VERONICA",
        "TODESCO MATTIA",
        "TONIETTO FILIPPO",
        "VIGNAGA MATTEO",
        "VIGNOTTO SAMUELE",
        "VOGLI VULLNET",
        "YANG YIDE",
        "YE TAO REN FEDERICO",
        "ZACCONE ROSARIO",
        "ZANESCO LUCA",
        "ZONTA ROCHA FILIPPO",
        "ZULIANI GIOVANNI"
        };

    string primo_appello[] = {
        "AGAFITEI CIPRIAN",
        "ANDREETTO ALESSIO",
        "BALDO LEONARDO",
        "BANZATO ALESSIO",
        "BARBIERO LINDA",
        "BARRACO ALESSIO",
        "BARUTTA ANDREA",
        "BASSO LEONARDO",
        "BENCIVELLI LORENZO",
        "BENETAZZO ANTONIO",
        "BETTIN MICHELE",
        "BILINSKI ELEONORA",
        "BISCONTIN GIULIO",
        "BOMBEN FILIPPO",
        "BOTTACIN GIULIO",
        "BRESOLIN GIANLUCA",
        "BRESSAN STEFANO",
        "BROTTO DAVIDE",
        "BROTTO ROMINA",
        "BUSTREO ALESSANDRO",
        "CALEARO ROMEO",
        "CAMILLO MATTEO",
        "CANIATO SABRINA",
        "CAPPELLARI MARCO",
        "CAREGNATO SIMONE",
        "CARLESSO NICCOLÒ",
        "CARRARO ALESSANDRO",
        "CARRARO RICCARDO",
        "CARRETTA JESSICA",
        "CAVALLI RICCARDO",
        "CECCHIN ANDREA",
        "CINEL ALBERTO",
        "COSTANTIN RICCARDO ALBERTO",
        "COSTANTINI OSCAR",
        "CURCIO DAVIDE ANTONIO",
        "DALLA POZZA MATTIA",
        "DE LAURENTIS ARIANNA PIA",
        "DIOTTO DAVIDE",
        "DOMUTA ALESSIA",
        "DONANZAN DAVIDE",
        "D'OVIDIO GIACOMO",
        "DUGO ALBERTO",
        "EGIDI ANNALISA",
        "FAVARON RICCARDO",
        "FELTRIN ALESSANDRO",
        "FELTRIN EMANUELE",
        "FERRO ELENA",
        "FILIPPINI GIOVANNI",
        "FLORIAN EDOARDO",
        "FONTANA RAFFAELE PAOLO",
        "FRIGO LEONARDO",
        "FURIOSO PATRICK",
        "FURNO FRANCESCO",
        "GALLO EDOARDO",
        "GIACOMUZZO FRANCESCO",
        "GIURISATO ANDREA",
        "GOBBO MARCO",
        "GRANT JOSEPH",
        "GUALATO GIACOMO",
        "GUARDA MATTEO",
        "GUSATTO DEREK",
        "HASANI MATISA",
        "HU GIULIA",
        "HYSA ENDI",
        "IGBINEDION OSAMWONYI EGHOSA MATTEO",
        "KALAJ NANCY",
        "LAGO LEONARDO",
        "LAPENNA FRANCESCO",
        "LAZZARIN NICOLA",
        "LEONETTI ELIA",
        "LEONI PEDRO",
        "LEWENTAL SEBASTIANO",
        "LOVATO YURI",
        "MAHDI MOUAD",
        "MALGARISE DAVIDE",
        "MANGOLINI ANDREA",
        "MANIERO MANUEL",
        "MARANA SEBASTIANO",
        "MARCHIORATO PIETRO GIOVANNI",
        "MARCHIORO MICHELE",
        "MENEGHINI FABIO",
        "MENON GIOVANNI",
        "META ANITA",
        "MICHELAZZO ALBERTO",
        "MICHELON RICCARDO",
        "MORETTI GIOVANNI",
        "NIAGU ANA MARIA",
        "NORDIO ANNA",
        "NOUR EL HADI HOSAM",
        "OGNIBEN MICHELE",
        "ORLANDI GIACOMO",
        "PANDOLFO MATTIA",
        "PARISE LUCA",
        "PASQUALOTTO LORENZO",
        "PASQUETTO RICCARDO",
        "PASSARELLA ALESSANDRO",
        "PELLEGRINELLI NICOLÒ",
        "PERIC MARKO",
        "PIANON RAUL",
        "PONSO GIOVANNI",
        "PORPORATI DAVIDE",
        "POZZA FRANCESCO",
        "PRETO NICOLA",
        "REZZI ANDREA",
        "RIZZO ALBERTO",
        "ROSSO CARLO",
        "ROSSON LORENZO",
        "ROVEA SILVIA",
        "SABBADIN FILIPPO",
        "SALAMI LORENZO",
        "SCANTAMBURLO ALEX",
        "SECURO LUCA",
        "SIGNORELLI IULIUS",
        "SKËNDERI LISIEN",
        "SOLDÀ MATTEO",
        "SPADARO MATTEO",
        "STOCCO TOMMASO",
        "TODESCO MATTIA",
        "TONIOLO RICCARDO",
        "TOSO GIACOMO",
        "VALDAGNO PIETRO",
        "VEDOVATO ALEX",
        "VERONESE ANDREA",
        "VETTORAZZO SIMONE",
        "VIGNAGA MATTEO",
        "VIGNOTTO SAMUELE",
        "VISENTIN SAMUELE",
        "VOGLI VULLNET",
        "YE TAO REN FEDERICO",
        "ZAMBON MICHELE THANU",
        "ZANESCO LUCA",
        "ZAUPA RICCARDO",
        "ZONTA ROCHA FILIPPO",
        "ZULIANI GIOVANNI"
    };

    int counter = 0;

    for(int i = 0; i < 127; i++) {
        for(int k = 0; k < 134; k++) {
            if(secondo_appello[i] == primo_appello[k])
                counter = counter + 1;
        }
    }
    cout << counter << endl;
    cout << "passing rate: " << 100 - (counter*100)/127 << "%" << endl;
}